In [1]:
import torch
import torch.nn as nn
import numpy as np

In [2]:
_ = torch.manual_seed(0)

### 課題
- 以下の関数cross_entropy_lossを完成させましょう
- pytorchにおいてはlnはtorch.logを使います。
![image.png](attachment:image.png)

In [7]:
def cross_entropy_loss(x, t):
    print("x:", type(x))
    print("x:", x.dtype)
    print("t:", t.dtype)
    print("x:", x.device)
    return -torch.sum(torch.log(x) * t, dim=1)

### 課題の確認
- 上記cross_entropy_loss関数が正しい結果を出力できているかを確認しましょう

In [8]:
x = torch.rand(2, 5)
print(x)

t = torch.randint(0, 5, (2,))
print(t)
t = torch.nn.functional.one_hot(t, num_classes=5)
print(t)

loss = cross_entropy_loss(x, t)
print(loss)

tensor([[0.4194, 0.5529, 0.9527, 0.0362, 0.1852],
        [0.3734, 0.3051, 0.9320, 0.1759, 0.2698]])
tensor([0, 0])
tensor([[1, 0, 0, 0, 0],
        [1, 0, 0, 0, 0]])
x: <class 'torch.Tensor'>
x: torch.float32
t: torch.int64
x: cpu
tensor([0.8689, 0.9851])
