In [1]:
import torch
import torch.nn as nn
import numpy as np

# Tensor用にdtypeとdeviceを定義
dtype = torch.float
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
print("device:", device)

device: cpu


In [2]:
_ = torch.manual_seed(0)

### 課題
- 以下の関数cross_entropy_lossを完成させましょう
- pytorchにおいてはlnはtorch.logを使います。
![image.png](attachment:image.png)

In [7]:
def cross_entropy_loss(x, t):
    return -torch.[A](torch.[B](x) * t, dim=1)  #-torch.sum(torch.log(x) * t, dim=1)

SyntaxError: ignored

### 課題の確認
- 上記cross_entropy_loss関数が正しい結果を出力できているかを確認しましょう

In [6]:
x = torch.rand(2, 5)
print(x)

t = torch.randint(0, 5, (2,))
print(t)
t = torch.nn.functional.one_hot(t, num_classes=5)
print(t)
t=t.to(dtype)

loss = cross_entropy_loss(x, t)
print(loss)

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074],
        [0.6341, 0.4901, 0.8964, 0.4556, 0.6323]])
tensor([1, 1])
tensor([[0, 1, 0, 0, 0],
        [0, 1, 0, 0, 0]])
tensor([0.2637, 0.7132])
